"""Adjusted business registration to exclude files

Revision ID: 4053560d3adb
Revises: a6547058c709
Create Date: 2024-04-22 23:20:03.064259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4053560d3adb'
down_revision = 'a6547058c709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('documents')
        batch_op.drop_column('video_demo_of_service_offered')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_demo_of_service_offered', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('documents', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
