"""Changed relationships

Revision ID: 763587a3e60c
Revises: e9c3d6e972be
Create Date: 2024-04-20 19:50:46.010533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763587a3e60c'
down_revision = 'e9c3d6e972be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_provider_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookings_customer_id_users'), 'users', ['customer_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_bookings_service_provider_id_service_providers'), 'service_providers', ['service_provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_service_provider_id_service_providers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_bookings_customer_id_users'), type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('service_provider_id')

    # ### end Alembic commands ###
