"""Changed relationships

Revision ID: 8dc4dcb35d03
Revises: 763587a3e60c
Create Date: 2024-04-20 20:01:37.651816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc4dcb35d03'
down_revision = '763587a3e60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_services_service_provider_id_service_providers'), 'service_providers', ['service_provider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_services_service_provider_id_service_providers'), type_='foreignkey')
        batch_op.drop_column('service_provider_id')

    # ### end Alembic commands ###
