"""Adjusted Switched Hours available to string

Revision ID: cf2c26dfd7a2
Revises: 4053560d3adb
Create Date: 2024-04-22 23:30:25.596484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2c26dfd7a2'
down_revision = '4053560d3adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.alter_column('hours_available',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_providers', schema=None) as batch_op:
        batch_op.alter_column('hours_available',
               existing_type=sa.String(length=255),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
