"""Added relationships between Payment, Bookings and Customer

Revision ID: f683940a0c90
Revises: 2ebbda05eb03
Create Date: 2024-04-20 20:26:29.783466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f683940a0c90'
down_revision = '2ebbda05eb03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payments_booking_id_bookings'), 'bookings', ['booking_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_payments_customer_id_users'), 'users', ['customer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_customer_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_payments_booking_id_bookings'), type_='foreignkey')
        batch_op.drop_column('customer_id')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
